storeConfig:
  maxWalSizeBytes: 10485760
  walDir: "./wal/node-4"

clusterConfig:
  nodeId: node-4
  startupMode: FOLLOWER
  members:
    node-1:
      host: localhost
      port: 9000
    node-2:
      host: localhost
      port: 9001
    node-3:
      host: localhost
      port: 9002
    node-4:
      host: localhost
      port: 9003

nodeConfig:
  maxLogBytes: 3000000
  logFlushIntervalMs: 3000

